language: node_js
sudo: required
node_js:
  - v6
  - v5
  - v4
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
services:
  - mongodb
  - postgresql
  - redis-server
  - cassandra
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c 'create database travis;' -U postgres
  - psql -c 'CREATE ROLE admin superuser;' -U postgres
  - psql -c 'ALTER ROLE admin WITH LOGIN;' -U postgres
  - psql -c 'create table clients (_id serial primary key, name VARCHAR(40) not null, "createdAt" timestamp not null, "updatedAt" timestamp  not null);' -U travis