language: node_js
sudo: required
node_js:
  - v6
  - v5
  - v4
  - '0.12'
  - '0.10'
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -U postgres -c 'create database "test";'
  - psql 'create table clients(_id serial primary key, name VARCHAR(40) not null, "createdAt" timestamp not null, "updatedAt" timestamp  not null);'