language: node_js
sudo: required
node_js:
  - v6
  - v5
  - v4
cache:
  bundler: true
  directories:
  - node_modules
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c 'create database travis;' -U postgres
  - psql -c 'CREATE ROLE admin superuser;' -U postgres
  - psql -c 'ALTER ROLE admin WITH LOGIN;' -U postgres
  - psql -c 'create table clients (_id serial primary key, name VARCHAR(40) not null, "createdAt" timestamp not null, "updatedAt" timestamp  not null);' -U travis
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
  - mongo --version
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.10/apache-cassandra-3.10-bin.tar.gz && tar -xvzf apache-cassandra-3.10-bin.tar.gz
  - sudo sh ./apache-cassandra-3.10/bin/cassandra -R
  - sleep 20
