language: node_js
sudo: required
node_js:
  - v6
  - v5
  - v4
  - '0.12'
  - '0.10'
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c 'CREATE ROLE admin superuser;' -U postgres
  - psql -c 'CREATE USER admin;' -U postgres
  - psql -c 'ALTER USER admin WITH admin;'
  - psql -c 'create table clients(_id serial primary key, name VARCHAR(40) not null, "createdAt" timestamp not null, "updatedAt" timestamp  not null);' -U postgres